"use strict";
console.log('Hello world!');
let nome = 'Mario';
let anni = 30;
let boolean = false;
let array = [20, 'testo', true];
let arrayString = ['testo'];
let arrayNumber = [20, 30, 40];
nome = 'marco';
let vuota;
vuota = 0;
